# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import controlplane_pb2 as controlplane__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controlplane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deploy = channel.unary_unary(
                '/mp.controlplane.v1.ControlPlane/Deploy',
                request_serializer=controlplane__pb2.DeployRequest.SerializeToString,
                response_deserializer=controlplane__pb2.Deployment.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/mp.controlplane.v1.ControlPlane/Rollback',
                request_serializer=controlplane__pb2.RollbackRequest.SerializeToString,
                response_deserializer=controlplane__pb2.Deployment.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/mp.controlplane.v1.ControlPlane/Kill',
                request_serializer=controlplane__pb2.KillRequest.SerializeToString,
                response_deserializer=controlplane__pb2.KillResponse.FromString,
                _registered_method=True)
        self.ListDeployments = channel.unary_unary(
                '/mp.controlplane.v1.ControlPlane/ListDeployments',
                request_serializer=controlplane__pb2.ListDeploymentsRequest.SerializeToString,
                response_deserializer=controlplane__pb2.ListDeploymentsResponse.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/mp.controlplane.v1.ControlPlane/Resolve',
                request_serializer=controlplane__pb2.ResolveRequest.SerializeToString,
                response_deserializer=controlplane__pb2.ResolveResponse.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def Deploy(self, request, context):
        """Serve a version on developer endpoints (canary) or to consumers (release).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Stop the current consumer deployment and bring back the one before it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """The kill switch: stop every deployment of a version and block it everywhere.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeployments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Used by the gateway: what serves a model in an environment, and is it blocked?
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=controlplane__pb2.DeployRequest.FromString,
                    response_serializer=controlplane__pb2.Deployment.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=controlplane__pb2.RollbackRequest.FromString,
                    response_serializer=controlplane__pb2.Deployment.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=controlplane__pb2.KillRequest.FromString,
                    response_serializer=controlplane__pb2.KillResponse.SerializeToString,
            ),
            'ListDeployments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeployments,
                    request_deserializer=controlplane__pb2.ListDeploymentsRequest.FromString,
                    response_serializer=controlplane__pb2.ListDeploymentsResponse.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=controlplane__pb2.ResolveRequest.FromString,
                    response_serializer=controlplane__pb2.ResolveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mp.controlplane.v1.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mp.controlplane.v1.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mp.controlplane.v1.ControlPlane/Deploy',
            controlplane__pb2.DeployRequest.SerializeToString,
            controlplane__pb2.Deployment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mp.controlplane.v1.ControlPlane/Rollback',
            controlplane__pb2.RollbackRequest.SerializeToString,
            controlplane__pb2.Deployment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mp.controlplane.v1.ControlPlane/Kill',
            controlplane__pb2.KillRequest.SerializeToString,
            controlplane__pb2.KillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mp.controlplane.v1.ControlPlane/ListDeployments',
            controlplane__pb2.ListDeploymentsRequest.SerializeToString,
            controlplane__pb2.ListDeploymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mp.controlplane.v1.ControlPlane/Resolve',
            controlplane__pb2.ResolveRequest.SerializeToString,
            controlplane__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
